import "../../css/style.css";
import { phoneArrow } from "../modules/phoneArrow";
import { menu } from "../modules/menu";
import { smoothScroll } from "../modules/smoothScroll";
import { modal } from "../modules/modal";
import { phoneNum } from "../modules/phoneNum";
import { sendData } from "../modules/sendData";
import { privacyPopup } from "../modules/privacyPopup";
import { numbersClues } from "../modules/numbersClues";
import { repairTypes } from "../modules/repairTypes";
import { portfolio } from "../modules/portfolio";
import { contract } from "../modules/contract";
import { consult } from "../modules/consult";
import { feedback } from "../modules/feedback";
import { faq } from "../modules/faq";
import { renderRepairTypes } from "../modules/renderRepairTypes";

phoneArrow();
menu();
smoothScroll();
modal();
phoneNum();
sendData();
privacyPopup();
numbersClues();
repairTypes();
portfolio();
contract();
consult();
feedback();
faq();
renderRepairTypes();